name: merge
version: 0.1.0
author: Joseph Moniz <joseph.moniz@gmail.com>
description: A Stream transformer for merging multiple streams into one w/ concurrency
homepage: https://github.com/JosephMoniz/dart-merge
dependencies:
  composite_subscription: '>=0.1.0 <0.2.0'
  flat_map:
    git: https://github.com/cajurabi/dart-flat-map.git
    version: '>=0.1.0 <0.2.0'
